### ISSUE TITLE
What file do you modify for the arguments?

### ISSUE THREAD

**Issue by czadikem** [adamthole/PyPotter#2]
Hi @adamthole I was wondering what file or files I have to modify to put all this in
![Screenshot from 2020-01-07 11-57-12](https://user-images.githubusercontent.com/35937408/71920872-f23f6700-3144-11ea-9c44-6e3b1d9299e1.png)

**Comment by adamthole** [comment]
Hi @czadikem,

You don't need to modify any of those files to use the required arguments.  Not needing to modify the files is the entire reason I used command line arguments.  They are command line arguments that you will put in when you call PyPotter.py.  For example:

python3 PyPotter.py http://192.168.1.107:8080/?action=stream https://mydomain.duckdns.org:8123 your_api_token

I hope that answers your question.
